dist: trusty
language: python
cache: pip
matrix:
    include:
        - python: 2.7
          env: KERAS_BACKEND=tensorflow TEST_MODE=PEP8
        - python: 2.7
          env: KERAS_BACKEND=tensorflow
        - python: 3.6
          env: KERAS_BACKEND=tensorflow
        # - python: 2.7
        #   env: KERAS_BACKEND=theano
        # - python: 3.6
        #   env: KERAS_BACKEND=theano

install:
  - pip install pytest pytest-pep8 pytest-cov

  # install TensorFlow
  - pip install tensorflow

  #- pip install theano

  # Install package and test requirements.
  - pip install -e .[tests]

  # for spacy
  - "python -m spacy download en"

script:
  # run keras backend init to initialize backend config
  - python -c "import keras.backend"
  # set up keras backend
  - sed -i -e 's/"backend":[[:space:]]*"[^"]*/"backend":\ "'$KERAS_BACKEND'/g' ~/.keras/keras.json;
  - echo -e "Running tests with the following config:\n$(cat ~/.keras/keras.json)"
  - if [[ "$TEST_MODE" == "PEP8" ]]; then
      PYTHONPATH=$PWD:$PYTHONPATH py.test --pep8 -m pep8;
    else
      PYTHONPATH=$PWD:$PYTHONPATH/tests py.test;
    fi
