site_name: Documentation Text Classification Keras
theme: readthedocs
docs_dir: sources
repo_url: http://github.com/jfilter/text-classification-keras
edit_uri: blob/master/docs/templates
site_description: 'Documentation Text Classification Keras - Text Classification Library for Keras'

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - css/extras.css

markdown_extensions:
  - mdx_math

pages:
  - Home: index.md
  - API Docs:
    - Models:
      - Sequence Processing Models: texcla.models.sequence_encoders.md
      - Sequence Model Builder Factory: texcla.models.token_model.md
      - Sentence Model Builder Factory: texcla.models.sentence_model.md
      - Custom Layers: texcla.models.layers.md
    - Preprocessing:
      - Word Tokenizer: texcla.preprocessing.word_tokenizer.md
      - Sentence Tokenizer: texcla.preprocessing.sentence_tokenizer.md
      - Tokenizer: texcla.preprocessing.tokenizer.md
      - Char Tokenizer: texcla.preprocessing.char_tokenizer.md
      - Utils: texcla.preprocessing.utils.md
    - Embeddings: texcla.embeddings.md
    - Experiment: texcla.experiment.md
    - Corpus: texcla.corpus.md
    - Data: texcla.data.md
    - Utils:
        - Format: texcla.utils.format.md
        - Generators: texcla.utils.generators.md
        - IO: texcla.utils.io.md
        - Sampling: texcla.utils.sampling.md

