site_name: Documentation Text Classification Keras
theme: readthedocs
docs_dir: sources
repo_url: http://github.com/jfilter/text-classification-keras
edit_uri: blob/master/docs/templates
site_description: 'Documentation Text Classification Keras - Text Classification Library for Keras'

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - css/extras.css

markdown_extensions:
  - mdx_math

pages:
  - Home: index.md
  - API Docs:
    - Models:
      - Sequence Processing Models: keras_text.models.sequence_encoders.md
      - Sequence Model Builder Factory: keras_text.models.token_model.md
      - Sentence Model Builder Factory: keras_text.models.sentence_model.md
      - Custom Layers: keras_text.models.layers.md
    - Preprocessing:
      - Word Tokenizer: keras_text.preprocessing.word_tokenizer.md
      - Sentence Tokenizer: keras_text.preprocessing.sentence_tokenizer.md
      - Tokenizer: keras_text.preprocessing.tokenizer.md
      - Char Tokenizer: keras_text.preprocessing.char_tokenizer.md
      - Utils: keras_text.preprocessing.utils.md
    - Embeddings: keras_text.embeddings.md
    - Experiment: keras_text.experiment.md
    - Corpus: keras_text.corpus.md
    - Data: keras_text.data.md
    - Utils:
        - Format: keras_text.utils.format.md
        - Generators: keras_text.utils.generators.md
        - IO: keras_text.utils.io.md
        - Sampling: keras_text.utils.sampling.md

